/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(4700f5a9-0a54-4ba7-8642-5410eca17785)]
interface nsIPlatformInfo : nsISupports
{
  /**
   * The TRUE version of the runtime.
   */
  readonly attribute ACString runtimeVersion;

  /**
   * Deprecated: The version of the XULRunner platform.
   * Always returns "52.9.0"
   */
  readonly attribute ACString platformVersion;

  /**
   * The build ID/date of gecko and the XULRunner platform.
   */
  readonly attribute ACString platformBuildID;
};
